apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  namespace: epa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: evan182/app1:latest
        ports:
        - containerPort: 3000
        env:
        - name: APP2_URL
          value: "http://app2-service:3000"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: epa
spec:
  selector:
    app: app1
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
