apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-deployment
  namespace: epa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: evan182/app2:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /hello
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: epa
spec:
  selector:
    app: app2
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
